projectName: PlusAsTab
projectUrl: https://joelpurra.com/projects/plusastab/
projectRedirectBaseUrl: https://joelpurra.com/projects/plusastab/docs
projectGithub: https://github.com/joelpurra/plusastab
projectStackoverflow: https://stackoverflow.com/search?q=plusastab
